2024-07-06 09:22:38,456 - root - main.py - ERROR - <module> - Testing saving logs to file.
